### PR TITLE
Js feature

### PR DESCRIPTION
**Pull request by UmerZia**
Hello 👋, In this PR I:
- create card section dynamically using js
- create a dynamic modal when the user clicks on the card modal will be created and upon clicking on the cross the modal will be removed.

### CODE REVIEW

**Review by mgmediaweb — CHANGES_REQUESTED** [review]
Hi @UmerZia , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

almost1

## Highlights 💯 
- Professional-looking readme file. ✔️ 
- Clean and tidy code. ✔️ 
- Good job following the design. ✔️ 

## Required Changes ♻️
- Kindly, I suggest you create more descriptive Pull Request so that the reviewers can know what you are submitting.
- Kindly, I suggest that the "live demo" link always shows the version of your site you are presenting (currently it shows an old version with errors)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- It would be excellent if it could show different content in each job so that the information displayed in each popup would be different.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by UmerZia** [comment]
### Thank you for the review 😄 I applied the above-mentioned issues.
- I add the source link and live preview link to the 'see live' and 'source' buttons.
- I changed the tech name to that you can see that every time a different modal is generated via js.
- I will keep that in mind and next time I try to create more descriptive PR.

**Review by mgmediaweb — CHANGES_REQUESTED** [review]
Hi @UmerZia , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

almost5

 ## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

 ## Required Changes ♻️

Kindly, the LIVE DEMO link in your README file still points to a branch that is not the one you are presenting now, please make the corresponding change

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by UmerZia** [comment]
I add the live link of the current branch

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED ✔🍾🎉**
Hello @UmerZia 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
